---
title: "051322 Miraligner"
output: html_document
date: '2022-05-13'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("/Volumes/Gak/seqcluster/miraligner")
library(isomiRs)
control <- "control"
stroke <- "stroke"
de <- data.frame(row.names = c("1","3","4","8","9","13","14","18","19","20","21","22","23","24","30","31","33","34","35","36","37","38","41","43","44","47","48","50","53","54","55","56","57","61","62","63","65","69","70","72","73","74","76","78","79","81","84","86","87","88","91","92","9394","95","96","97","98","107","110","113","115","117","118","121","122","124","126","131","133","134","135","137","140","141","142"), condition = c(control,control,control,stroke,control,control,stroke,control,stroke,control,control,control,control,control,stroke,stroke,stroke,stroke,stroke,stroke,stroke,stroke,control,stroke,control,control,stroke,control,control,stroke,control,control,control,stroke, control,control,control,stroke,stroke,stroke,control,stroke,control,stroke,stroke,control,stroke,control,control,control,control,stroke,stroke,stroke,stroke,stroke,control,control,control,control,stroke,stroke,control,control,control,stroke,control,stroke,stroke,control,control,stroke,control,control,control))
fn_list <- list.files(path = ".", pattern="mirna", full.names = TRUE)
#ids <- IsomirDataSeqFromFiles("./fast_31p_trim_freq.mirna", coldata = de)

#head(counts(ids))
```

```{r}
library(tidyverse)
library(data.table)
library(DESeq2)
library(ShortRead)
library(Biostrings)
library(stringdist)
library(pryr)

rm(list = ls())

source("/Volumes/Gak/seqcluster/UMI-tools-test/UMIc/R/casesWorkflows.R")
source("/Volumes/Gak/seqcluster/UMI-tools-test/UMIc/R/functions.R")

#type of data - paired or single
pairedData <- F

#UMI located in Read1 --> "R1"
#UMI located in Read1 and Read2 --> "R1 & R2"
UMIlocation <- "R1"

#length of the UMI
UMIlength <- 12

#length of th sequence
sequenceLength <- 25

#min read counts per UMI, for initial data cleaning
countsCutoff <- 5

#max UMI distance for UMI merging
UMIdistance <- 1

#max sequence distance for UMI correction
sequenceDistance <- 3

#inputs folder / working directory
inputsFolder <- "/Volumes/Gak/seqcluster/UMI-tools-test/dedup_2"

#outputs folder
outputsFolder <- "/Volumes/Gak/seqcluster/UMI-tools-test/dedup"
```

```{r}
if (pairedData & UMIlocation == "R1"){   #case 1 -- paired data and UMI only in Read1
  
  inputFiles <- list.files(inputsFolder, pattern = "fastq") 
  
  while(length(inputFiles) > 0){
    
    file1 <- inputFiles[1]
    
    commonPart <- as.character(str_split(file1,"R1", simplify = T))
    commonPart <- commonPart[length(commonPart)]
    
    file2 <- str_replace(file1,paste0("R1",commonPart),paste0("R2",commonPart))
    
    filepath1 <- paste0(inputsFolder,"/",file1)
    filepath2 <- paste0(inputsFolder,"/",file2)
    
    pairedR1(filepath1, 
             filepath2, 
             outputsFolder, 
             UMIlength, 
             UMIdistance, 
             sequenceLength, 
             sequenceDistance, 
             countsCutoff)
    
    inputFiles <- inputFiles[str_detect(inputFiles,paste0(file1,"|",file2), negate = T)]
  }
 
  
} else if (pairedData & UMIlocation == "R1 & R2"){   #case 2 -- paired data and UMI in Read1 and Read2
  
  inputFiles <- list.files(inputsFolder, pattern = "fastq") 
  
  while(length(inputFiles) > 0){
    
    file1 <- inputFiles[1]
    
    commonPart <- as.character(str_split(file1, "R1", simplify = T))
    commonPart <- commonPart[length(commonPart)]
    
    file2 <- str_replace(file1, 
                         paste0("R1", commonPart), 
                         paste0("R2", commonPart))
    
    filepath1 <- paste0(inputsFolder, "/", file1)
    filepath2 <- paste0(inputsFolder, "/", file2)
    
    cat(c("Files:", file1, file2, "\n"))

    pairedR1R2(filepath1, 
               filepath2, 
               outputsFolder, 
               UMIlength, 
               UMIdistance, 
               sequenceLength, 
               sequenceDistance, 
               countsCutoff)
    
    
    inputFiles <- inputFiles[str_detect(inputFiles, paste0(file1, "|", file2), negate = T)]
  }

  
} else if (!pairedData){  #case 3 -- single data
  
  inputFiles <- list.files(inputsFolder, pattern = "fastq") 
  
  while(length(inputFiles) > 0){
    
    file1 <- inputFiles[1]
    
    filepath1 <- paste0(inputsFolder,"/",file1)

    single(filepath1, 
           outputsFolder, 
           UMIlength, 
           UMIdistance, 
           sequenceLength, 
           sequenceDistance, 
           countsCutoff)
    
    inputFiles <- inputFiles[str_detect(inputFiles,file1, negate = T)]
  }
 
}  

```

